In [1]:
import pandas as pd 
import numpy as np

/var/folders/0d/2kwkrk3j5j373ss9sbf8sd6m0000gn/T/ipykernel_15042/1228117823.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [5]:
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [6]:
df = pd.read_csv('train.csv', usecols=['Age', 'Fare', 'Survived'])

In [7]:
df.dropna(inplace=True)

In [8]:
df.shape

(714, 3)

In [9]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [10]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [11]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [12]:
X_train.head(2)

      Age     Fare
328  31.0  20.5250
73   26.0  14.4542

In [13]:
clf = DecisionTreeClassifier()

In [14]:
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [15]:
accuracy_score(y_test , y_pred)

0.6293706293706294

In [16]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

0.6274843505477307