In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("ps 3.csv")

In [3]:
df.head()

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,Skill_Gap_Score,Readiness_Score,Employment_Status,Industry,Annual_Salary_USD,Career_Readiness_Level
0,0x1,NaN,Diploma,0.6,Cybersecurity Analyst,61,51-56,65,0,310,41.87,47.35,Unemployed,NaN,118274 USD,Medium
1,2,NaN,NaN,8.4,?,"{""v"": 59}",MISSING,MISSING,2,"{""v"": 175}",50.91,"{""v"": 79.52}",?,MISSING,32296,High
2,3,NaN,Bachelor,7.3-12.3,tsylanA ataD,48,"{""v"": 57}",92,7,35,30.15,47.31,Unemployed,UmV0YWls,26393,Low
3,4,"{""v"": 25}",Diploma,11.2,NaN,49,42-47,"{""v"": 94}",2,301,"{""v"": 42.46}",87.86-92.86,NaN,Finance,20121,High
4,0x5,38,MISSING,0.4,NaN,NaN,66,66,?,291,90.29-95.29,MISSING,deyolpmE,Healthcare,25655,TG93

In [4]:
df.sample(5)

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,Skill_Gap_Score,Readiness_Score,Employment_Status,Industry,Annual_Salary_USD,Career_Readiness_Level
29504,0x7341,?,High School,1.3,Cloud Engineer,NaN,NaN,48,"{""v"": 0}",82,Val_84.35,44.56,Unemployed,NaN,106293,High
33002,0x80eb,47-52,PhD,NaN,Cloud Engineer,56,41,92,0,Val_172,30.99,85.66,Student,IT,115125,Medium
16829,0x41be,29,RGlwbG9tYQ==,"{""v"": 7.0}",ML Engineer,55,NaN,69,3-8,293,NaN,47.83,Unemployed,Manufacturing,$141058,NaN
32157,32158,40-45,RGlwbG9tYQ==,Val_9.1,Software Engineer,NaN,56,?,2,404,NaN,Val_41.73,Employed,Education,78180,SGlnaA==
14570,0x38eb,Val_29,retsaM,0.7,MISSING,NaN,63,88,Val_3,Val_254,4.59,21.54,RW1wbG95ZWQ=,Education,NaN,Low

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        50000 non-null  object
 1   Age                       43907 non-null  object
 2   Education_Level           43984 non-null  object
 3   Years_of_Experience       43923 non-null  object
 4   Current_or_Target_Role    43992 non-null  object
 5   Technical_Skill_Score     44121 non-null  object
 6   Soft_Skill_Score          43954 non-null  object
 7   Domain_Knowledge_Score    44089 non-null  object
 8   Certification_Count       43940 non-null  object
 9   Training_Hours_Last_Year  43979 non-null  object
 10  Skill_Gap_Score           44029 non-null  object
 11  Readiness_Score           43930 non-null  object
 12  Employment_Status         44045 non-null  object
 13  Industry                  43939 non-null  object
 14  Annual_Salary_USD         44073 non-null  object
 15  Career_Readiness_Level    43991 non-null  object
dtypes: object(16)
memory usage: 6.1+ MB

In [6]:
df.describe()

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,Skill_Gap_Score,Readiness_Score,Employment_Status,Industry,Annual_Salary_USD,Career_Readiness_Level
count,50000,43907,43984,43923,43992,44121,43954,44089,43940,43979,44029,43930,44045,43939,44073,43991
unique,50000,170,17,1076,23,242,242,242,34,2002,19244,19267,11,20,36945,11
top,0x1,MISSING,High School,?,Software Engineer,MISSING,?,?,2,?,?,MISSING,Employed,Healthcare,?,High
freq,1,2022,4803,2061,3501,1979,2022,1943,3567,1982,2028,2087,8162,4118,2034,7932

In [7]:
df.isna().sum()

ID                             0
Age                         6093
Education_Level             6016
Years_of_Experience         6077
Current_or_Target_Role      6008
Technical_Skill_Score       5879
Soft_Skill_Score            6046
Domain_Knowledge_Score      5911
Certification_Count         6060
Training_Hours_Last_Year    6021
Skill_Gap_Score             5971
Readiness_Score             6070
Employment_Status           5955
Industry                    6061
Annual_Salary_USD           5927
Career_Readiness_Level      6009
dtype: int64

In [11]:
df.head()

0    <bound method Series.mean of 0              Na...
1    <bound method Series.mean of 0              Na...
2    <bound method Series.mean of 0              Na...
3                                            {"v": 25}
4                                                   38
Name: Age, dtype: object

In [9]:
df.head()

0    <bound method Series.mean of 0              Na...
1    <bound method Series.mean of 0              Na...
2    <bound method Series.mean of 0              Na...
3                                            {"v": 25}
4                                                   38
Name: Age, dtype: object