In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("ps 3.csv")

In [3]:
df.head()

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,Skill_Gap_Score,Readiness_Score,Employment_Status,Industry,Annual_Salary_USD,Career_Readiness_Level
0,0x1,NaN,Diploma,0.6,Cybersecurity Analyst,61,51-56,65,0,310,41.87,47.35,Unemployed,NaN,118274 USD,Medium
1,2,NaN,NaN,8.4,?,"{""v"": 59}",MISSING,MISSING,2,"{""v"": 175}",50.91,"{""v"": 79.52}",?,MISSING,32296,High
2,3,NaN,Bachelor,7.3-12.3,tsylanA ataD,48,"{""v"": 57}",92,7,35,30.15,47.31,Unemployed,UmV0YWls,26393,Low
3,4,"{""v"": 25}",Diploma,11.2,NaN,49,42-47,"{""v"": 94}",2,301,"{""v"": 42.46}",87.86-92.86,NaN,Finance,20121,High
4,0x5,38,MISSING,0.4,NaN,NaN,66,66,?,291,90.29-95.29,MISSING,deyolpmE,Healthcare,25655,TG93

In [4]:
df.sample(5)

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,Skill_Gap_Score,Readiness_Score,Employment_Status,Industry,Annual_Salary_USD,Career_Readiness_Level
20638,0x509f,20,Diploma,9.8-14.8,Software Engineer,78,?,?,Val_3,471,Val_53.81,20.84-25.84,Unemployed,Finance,22030,NaN
14825,14826,NaN,QmFjaGVsb3I=,24.8,Software Engineer,Val_60,"{""v"": 94}",?,1,NaN,42.43,63.59,Employed,MISSING,143556 USD,TG93
42043,0xa43c,NaN,TWFzdGVy,0.4,NaN,Val_84,Val_77,86,0,423,41.19,?,Employed,RWR1Y2F0aW9u,NaN,High
36614,36615,19,Master,7.2,System Admin,74,77,"{""v"": 81}",7-12,391,70.14-75.14,59.59,MISSING,Finance,91605,SGlnaA==
7191,7192,MISSING,QmFjaGVsb3I=,MISSING,Data Analyst,72,61,79,NaN,"{""v"": 433}",8.89,35.1,Unemployed,RWR1Y2F0aW9u,?,Low

In [ ]:
df['Age'].fillna(0)

0                0
1                0
2                0
3        {"v": 25}
4               38
           ...
49995            0
49996           34
49997            0
49998        41-46
49999           26
Name: Age, Length: 50000, dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        50000 non-null  object
 1   Age                       43907 non-null  object
 2   Education_Level           43984 non-null  object
 3   Years_of_Experience       43923 non-null  object
 4   Current_or_Target_Role    43992 non-null  object
 5   Technical_Skill_Score     44121 non-null  object
 6   Soft_Skill_Score          43954 non-null  object
 7   Domain_Knowledge_Score    44089 non-null  object
 8   Certification_Count       43940 non-null  object
 9   Training_Hours_Last_Year  43979 non-null  object
 10  Skill_Gap_Score           44029 non-null  object
 11  Readiness_Score           43930 non-null  object
 12  Employment_Status         44045 non-null  object
 13  Industry                  43939 non-null  object
 14  Annual_Salary_USD         44073 non-null  object
 15  Career_Readiness_Level    43991 non-null  object
dtypes: object(16)
memory usage: 6.1+ MB

In [6]:
df.describe()

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,Skill_Gap_Score,Readiness_Score,Employment_Status,Industry,Annual_Salary_USD,Career_Readiness_Level
count,50000,43907,43984,43923,43992,44121,43954,44089,43940,43979,44029,43930,44045,43939,44073,43991
unique,50000,170,17,1076,23,242,242,242,34,2002,19244,19267,11,20,36945,11
top,0x1,MISSING,High School,?,Software Engineer,MISSING,?,?,2,?,?,MISSING,Employed,Healthcare,?,High
freq,1,2022,4803,2061,3501,1979,2022,1943,3567,1982,2028,2087,8162,4118,2034,7932

In [7]:
df.isna().sum()

ID                             0
Age                         6093
Education_Level             6016
Years_of_Experience         6077
Current_or_Target_Role      6008
Technical_Skill_Score       5879
Soft_Skill_Score            6046
Domain_Knowledge_Score      5911
Certification_Count         6060
Training_Hours_Last_Year    6021
Skill_Gap_Score             5971
Readiness_Score             6070
Employment_Status           5955
Industry                    6061
Annual_Salary_USD           5927
Career_Readiness_Level      6009
dtype: int64

In [13]:
df=pd.get_dummies(df, columns=['Career_Readiness_Level'],dtype=int,drop_first=True)

In [14]:
df.head()

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,...,Career_Readiness_Level_High,Career_Readiness_Level_Low,Career_Readiness_Level_MISSING,Career_Readiness_Level_Medium,Career_Readiness_Level_SGlnaA==,Career_Readiness_Level_TG93,Career_Readiness_Level_TWVkaXVt,Career_Readiness_Level_hgiH,Career_Readiness_Level_muideM,Career_Readiness_Level_woL
0,0x1,NaN,Diploma,0.6,Cybersecurity Analyst,61,51-56,65,0,310,...,0,0,0,1,0,0,0,0,0,0
1,2,NaN,NaN,8.4,?,"{""v"": 59}",MISSING,MISSING,2,"{""v"": 175}",...,1,0,0,0,0,0,0,0,0,0
2,3,NaN,Bachelor,7.3-12.3,tsylanA ataD,48,"{""v"": 57}",92,7,35,...,0,1,0,0,0,0,0,0,0,0
3,4,"{""v"": 25}",Diploma,11.2,NaN,49,42-47,"{""v"": 94}",2,301,...,1,0,0,0,0,0,0,0,0,0
4,0x5,38,MISSING,0.4,NaN,NaN,66,66,?,291,...,0,0,0,0,0,1,0,0,0,0

In [11]:
df.drop(columns=['Career_Readiness_Level_MISSING','Career_Readiness_Level_SGlnaA==','Career_Readiness_Level_TG93','Career_Readiness_Level_TWVkaXVt'],inplace=True)

KeyError: "['Career_Readiness_Level_MISSING', 'Career_Readiness_Level_SGlnaA==', 'Career_Readiness_Level_TG93', 'Career_Readiness_Level_TWVkaXVt'] not found in axis"

In [15]:
df.drop(columns=['Career_Readiness_Level_MISSING','Career_Readiness_Level_SGlnaA==','Career_Readiness_Level_TG93','Career_Readiness_Level_TWVkaXVt'], inplace=True)

In [17]:
df

,ID,Age,Education_Level,Years_of_Experience,Current_or_Target_Role,Technical_Skill_Score,Soft_Skill_Score,Domain_Knowledge_Score,Certification_Count,Training_Hours_Last_Year,...,Readiness_Score,Employment_Status,Industry,Annual_Salary_USD,Career_Readiness_Level_High,Career_Readiness_Level_Low,Career_Readiness_Level_Medium,Career_Readiness_Level_hgiH,Career_Readiness_Level_muideM,Career_Readiness_Level_woL
0,0x1,NaN,Diploma,0.6,Cybersecurity Analyst,61,51-56,65,0,310,...,47.35,Unemployed,NaN,118274 USD,0,0,1,0,0,0
1,2,NaN,NaN,8.4,?,"{""v"": 59}",MISSING,MISSING,2,"{""v"": 175}",...,"{""v"": 79.52}",?,MISSING,32296,1,0,0,0,0,0
2,3,NaN,Bachelor,7.3-12.3,tsylanA ataD,48,"{""v"": 57}",92,7,35,...,47.31,Unemployed,UmV0YWls,26393,0,1,0,0,0,0
3,4,"{""v"": 25}",Diploma,11.2,NaN,49,42-47,"{""v"": 94}",2,301,...,87.86-92.86,NaN,Finance,20121,1,0,0,0,0,0
4,0x5,38,MISSING,0.4,NaN,NaN,66,66,?,291,...,MISSING,deyolpmE,Healthcare,25655,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,NaN,SGlnaCBTY2hvb2w=,0.1,Software Engineer,82,73,78,0,160,...,12.07,Unemployed,SGVhbHRoY2FyZQ==,80899,1,0,0,0,0,0
49996,49997,34,?,Val_17.3,reenignE duolC,72,55,74,1,Val_90,...,71.08,Employed,SVQ=,51223 USD,1,0,0,0,0,0
49997,49998,NaN,Master,NaN,System Admin,65,43,?,1-6,"{""v"": 389}",...,28.18,Employed,UmV0YWls,$139655,0,0,1,0,0,0
49998,49999,41-46,QmFjaGVsb3I=,3.0-8.0,TUwgRW5naW5lZXI=,50,"{""v"": 49}",NaN,"{""v"": 1}",NaN,...,54.07,VW5lbXBsb3llZA==,Manufacturing,54558,0,0,0,0,0,0
49999,50000,26,NaN,1.3,ML Engineer,"{""v"": 73}",NaN,91-96,3,87,...,0.14,RW1wbG95ZWQ=,NaN,127126,0,0,1,0,0,0

In [ ]:
df